# Site settings
name: MIAPPE
group: Minimum Information about A Plant Phenotyping Experiment
email: noreply@ebi.ac.uk
domain: //miappe.github.io
baseurl: /miappe-website
permalink: pretty

# Build settings
markdown: kramdown
